<?php
$labels = array();
$labels['autoresponder']  = 'Autorespond';
$labels['aliases'] = 'Aliases';
$labels['autoreply'] = "Send a notification";
$labels['autoreplybutton'] = 'Save';
$labels['autoreplymessage'] = 'Autoreply message';
$labels['autoreplysubject'] = 'Autoreply subject';
$labels['failed'] = 'Setting vacation failed!';
$labels['forward'] = 'Forwarding settings';
$labels['forwardingaddresses'] = 'Forward mail to';
$labels['keepcopy'] = 'Keep a copy of the mail';
$labels['mailforward'] = 'Mail Forwarding';
$labels['outofoffice'] = 'Vacation (Out of Office) Notification';
$labels['separate_alias'] = 'Separate each alias address by a comma';
$labels['separate_forward'] = 'Separate each forward address by a comma';
$labels['success_changed'] = 'Vacation settings succesfully changed';
$labels['vacation'] = 'Vacation';
// Button text
$labels['aliasesbutton'] = 'Get aliases';
// CPanel
$labels['interval'] = 'Interval; the number of hours to wait between responses to the same email address (empty will respond always)';
$labels['start'] = 'Start; date and time for the autoresponder to start (empty to start immediately)';
$labels['stop'] = 'Stop; date and time for the autoresponder to stop (empty will to never stop, date in the past to disable)';
$labels['html'] = 'This message body contains HTML';
?>