<?php
$labels = array();
$labels['autoresponder']  = 'Autoresponder';
$labels['aliases'] = 'Aliases';
$labels['autoreply'] = "Enviar una notificaci&oacute;n";
$labels['autoreplybutton'] = 'Guardar';
$labels['autoreplymessage'] = 'Mensaje de autorespuesta';
$labels['autoreplysubject'] = 'Asunto de autorespuesta';
$labels['failed'] = 'Fall&oacute; el cambio de vacaciones!';
$labels['forward'] = 'Configuraciones de reenvio';
$labels['forwardingaddresses'] = 'Reenviar el correo hacia';
$labels['keepcopy'] = 'Guardar una copia del correo';
$labels['mailforward'] = 'Reenvio de correo';
$labels['outofoffice'] = 'Notificacion de vacaciones (Fuera de la Oficina)';
$labels['separate_alias'] = 'Separe cada dirección de alias con una coma';
$labels['separate_forward'] = 'Separe cada dirección de reenvío con una coma';
$labels['success_changed'] = 'Configuraciones de vacaciones cambiadas satisfactoriamente';
$labels['vacation'] = 'Vacaciones';
// Button text
$labels['aliasesbutton'] = 'Obtener aliases';
// CPanel
$labels['interval'] = 'Intervalo; la cantidad de horas de espera entre las respuestas a la misma dirección de correo electrónico (vacío responderá siempre)';
$labels['start'] = 'Comienzo; fecha y hora de inicio de la respuesta automática (vacía para comenzar inmediatamente)';
$labels['stop'] = 'Detener; fecha y hora para que se detenga la respuesta automática (vacía para no parar nunca, fecha en el pasado para deshabilitar)';
$labels['html'] = 'El cuerpo de este mensaje contiene HTML';
?>